version: '3'

services:
  cache:
    container_name: dip_cache
    hostname: dip_cache
    image: redis

  server:
    container_name: dip_server
    hostname: dip_server
    build:
      context: ./server/
      dockerfile: Dockerfile
    image: dip_server
    command: >
      bash -xc "
        flask run --host=0.0.0.0
      "
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ./server:/dip/server
