# Generated by Django 3.0.2 on 2021-06-02 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20210601_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='photos.Photo'),
        ),
    ]
