# Generated by Django 3.0.2 on 2021-06-02 20:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20210602_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.PositiveIntegerField()),
                ('top', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('confidence', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_objects', to='photos.Photo')),
            ],
        ),
    ]
