# Generated by Django 3.0.2 on 2021-06-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_detectedobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
